spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tripflow
    username: tripflow
    password: tripflow

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer